name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        example:
          - "examples/arduino-blink"
          - "examples/espidf-hello-world"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -v -d ${{ matrix.example }}
